### ISSUE TITLE
Stack failed to create: [PutSubscriptionFilter] 

### ISSUE THREAD

**Issue by muram** [alertlogic/cloudwatch-logs-s3-export#9]
The nested stack failing at the subscription filter step when it attempts to send a test message to kinesis stream.

`19:23:00 UTC-0500	CREATE_FAILED	AWS::Logs::SubscriptionFilter	PutSubscriptionFilter	Could not deliver test message to specified Kinesis stream. Check if the given kinesis steam is in ACTIVE state.`

I’ve monitored the resource creation during the stack build and have observed that the dependent kinesis stream has been created and is in active state before the subscription is applied.

https://github.com/alertlogic/cloudwatch-logs-s3-export/blob/master/configuration/cloudformation/create-cwl-s3-export.template#L811

@BarrySkidmore

**Comment by muram** [comment]
Workaround (combined with @fss18 Welly's effort):

The pre-requisite is to have a Kinesis stream setup first and pass the ARN of the active stream as a CFT stack parameter. I uploaded the child + master templates into my temporary S3 bucket as a workaround until the [permanent improved solution](https://algithub.pd.alertlogic.net/alertlogic/alertlogic-aws-cwlcollect) is in place.

Master: https://s3.amazonaws.com/mmohamed-tools/templates/clw-to-s3-master-nested.template
Child: https://s3.amazonaws.com/mmohamed-tools/templates/clw-to-s3-child-nested.template

To run it:

1.	VPC Flow log must be enabled and the CloudWatch log group already setup
2.	Create new Kinesis stream (insure the stream is in Active state before running the stack)
3.	When creating new stack in CloudFromation, set the URL to the master template
4.	Enter all the parameters
5.	The master template will launch the child template

Once the stack is completed, you will start seeing logs stored in the dedicated S3 bucket. The stack will also create an IAM role and policy for setting up the IAM credentials in Log Manager (if you choose to automatically create the log source + credentials in the UI by providing an api key and account number).

**Comment by muram** [comment]
Re-opening to insure users are aware of the workaround for this issue.

**Comment by KoutilyaGowtham** [comment]
Is it necessary to have alertlogic account in the code

**Comment by muram** [comment]
@KoutilyaGowtham No this is optional for creating the log source in the UI automatically utilizing our API. You can leave all parameters under Alert Logic Log Manager Configuration empty.
